### ISSUE TITLE
Need "Map Terms" feature for Dictionary Extractor

### ISSUE THREAD

**Issue by avinashreddy07** [CODAIT/nlp-editor#101]
### Requirement
Map Terms feature will help user in grouping similar values under one key. Example - "_John works for IBM, stays in New York. Steve works for XYZ, stays in Texas_". If I implement Map Terms on this example, I could create a dictionary as follows - "_John-Person Name, Steve-Person Name, IBM-Organisation, XYZ-Organisation_".

### Background 
In Watson Knowledge Studio's Advanced Rule Editor (now deprecated), the user would select Map Terms feature while creating a dictionary as show in the below screenshot.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/25619001/191200879-cf83a5de-5f66-4657-a5f4-0448e8890966.png">

Json for reference -

```
{
  "annotations": {
    "Key_Alias": [
      {
        "Key_Alias": {
          "location": {
            "begin": 29,
            "end": 38
          },
          "text": "CONSIGNEE"
        },
        "Mapped_Term": "Consignee"
      },
      {
        "Key_Alias": {
          "location": {
            "begin": 128,
            "end": 135
          },
          "text": "INVOICE"
        },
        "Mapped_Term": "Invoice number"
      },
      {
        "Key_Alias": {
          "location": {
            "begin": 163,
            "end": 165
          },
          "text": "PO"
        },
        "Mapped_Term": "Purchase order number"
      },
      {
        "Key_Alias": {
          "location": {
            "begin": 366,
            "end": 375
          },
          "text": "CONSIGNEE"
        },
        "Mapped_Term": "Consignee"
      }
    ]
  },
  "instrumentationInfo": {
    "annotator": {
      "version": "1.1.0-2022-04-12T07:42:07.457Z",
      "key": "Custom Rule Editor"
    },
    "runningTimeMS": 15,
    "documentSizeChars": 723,
    "numAnnotationsTotal": 04,
    "numAnnotationsPerType": [
      {
        "annotationType": "Key_Alias",
        "numAnnotations": 04
      }
    ],
    "interrupted": false,
    "success": true
  }
}
```

Opening this issue, after discussing with @laurachiticariu .

**Comment by laurachiticariu** [comment]
@marthacryan attaching an example showcasing the structure of the XML files. Note that similar to the regular Dictionary case (Map terms = false), there are two XML files needed: one for the actual concept, and one for the content of the mapping table.

[FirstNameTest1_table.xml.txt](https://github.com/CODAIT/nlp-editor/files/9711776/FirstNameTest1_table.xml.txt)
[FirstNameTest1.xml.txt](https://github.com/CODAIT/nlp-editor/files/9711777/FirstNameTest1.xml.txt)

**Comment by laurachiticariu** [comment]
Example CSV file - note entries are quoted when the separator `,` is part of the entry (either in the first column or the second column). Any CSV reading library would understand this format.
```
Issue Date:,Invoice date
Inv date,Invoice date
"Invoice date, specified",Invoice date
```
