### ISSUE TITLE
"External Resource" check box is not functioning

### ISSUE THREAD

**Issue by avinashreddy07** [CODAIT/nlp-editor#103]
On WKS we used to create dynamic dictionary by checking check box External Resources and export the extractor. In the exported extractor, we can find a .csv file in resources folder (Please refer to the attached extractor .csv is located in the path - “_resources/KeyAliases/AliasesExtractorWithLemmaMatch/externalTable/_3bde19c0_e751_11ea_87b2_256990c62848_KeyAliases__Export__AliasesExtractorWithLemmaMatch_MappingTable.csv_”). In future user can modify the csv file and use the same dictionary extractor with out creating a new extractor. 
In the NLP-Editor we are having External Resources check box, but I observed that it is not functioning. 
I am attaching an extractor which is created on WKS for your reference

[AliasesExtractorWithLemmaMatch.zip](https://github.com/CODAIT/nlp-editor/files/9607453/AliasesExtractorWithLemmaMatch.zip)
.

**Comment by laurachiticariu** [comment]
@marthacryan can you take a look at this? the generated XML should have:

```
<dictionary-match case-sensitive="..." "external"="true">
```

**Comment by laurachiticariu** [comment]
This is a backend issue: the compiled model does not have a copy of the external dictionary. Re-assigning to @nysenthil .

**Comment by laurachiticariu** [comment]
Fix will be in v0.4.0.
