### ISSUE TITLE
Make Export implementation more self-contained

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#119]
The Export implementation simply surfaces the result of the last Run. If there were changes in the flow between the last Run action, Export does not include them. Instead, we'd like Export to recompile the flow and export it.

**Comment by nysenthil** [comment]
Hi @laurachiticariu  Martha did the frontend code changes needed for it and I completed the backend changes for it. I'm currently doing the integration testing and there are some minor problems which I'm discussing in #118 to get them resolved.
