### ISSUE TITLE
Checkmarkx fixed from v0.5.0 - contd

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#129]
The following remaining High issues reported by Checkmarkx file `NLP+Editor+0.7.pdf`:

![image](https://user-images.githubusercontent.com/16584976/214969927-8c81bf88-4029-4396-8116-fb23eaeb0455.png)

**Comment by marthacryan** [comment]
#139 fixed the reflected XSS and HSTS issues but not the stored XSS issues in the checkmarx scan. #140 was an effort to fix the stored XSS but didn't fix the checkmarx scan, so we closed the PR for now.
