### ISSUE TITLE
Unable to unzip systemT extractors after exporting from NLP Editor

### ISSUE THREAD

**Issue by avinashreddy07** [CODAIT/nlp-editor#136]
I am unable to unzip the exported systemT extractor from NLP Editor.

Note: I am using latest UI and backend container (01-ibm_watson_discovery_nlp_web_tool_backend_v0.5.0-06Dec2022.tar)

[backend_logs.txt](https://github.com/CODAIT/nlp-editor/files/10214100/backend_logs.txt)

[ui_logs.txt](https://github.com/CODAIT/nlp-editor/files/10214101/ui_logs.txt)

[Simple_Flow.json.zip](https://github.com/CODAIT/nlp-editor/files/10214106/Simple_Flow.json.zip)

[NLP_Canvas_Export(8).zip](https://github.com/CODAIT/nlp-editor/files/10214275/NLP_Canvas_Export.8.zip)

<img width="456" alt="image (3)" src="https://user-images.githubusercontent.com/25619001/207222424-ba58e0c3-7de9-45c7-81e4-e8b7c57e3f5c.png">

<img width="815" alt="image (4)" src="https://user-images.githubusercontent.com/25619001/207222433-b6036029-5feb-45c5-b7d8-96d4b52766b3.png">

**Comment by nysenthil** [comment]
Hi @avinashreddy07 

1) You had exported zip files before and tested them just fine. Do you now see this failure every time you export or only at certain times?

2) We have tested with Safari, Chrome and Firefox on Mac. It worked fine. By any chance, are you seeing this error on a browser running on Windows or Linux machine?

**Comment by laurachiticariu** [comment]
I am able to export on MacOS Monterrey 12.6 and the following browser:
- Firefox 107.0.1 (64-bit) and 108.0 (64-bit) - export works well.

I do see the error on these browsers:
- Chrome Version 108.0.5359.98 (Official Build) (x86_64); An older version of Chrome did work for me, so this is something that started happening only recently.
- On Safari Version 16.0 (17614.1.25.9.10, 17614)

**Comment by nysenthil** [comment]
I tested the Export feature on my Mac (v12.6 Monterey)  with the following browsers.

Firefox: v108.0 (64-bit)  
Safari Version 16.0 (17614.1.25.9.10, 17614)
Chrome: Version 108.0.5359.124

On Firefox and Safari on my Mac, it gets the exported zip file just fine with its expected file size. I'm able to unzip the downloaded zip file.

On Chrome, it downloads the exported zip file only partially. That will obviously cause error while unzipping.

@marthacryan Could you please check the frontend code logic where it does the download of the exported zip file to see why it is downloading only a partial zip file? You can print the size of the exported zip file that you find in the run-aql-result shared directory just before the file download logic is executed. It will give us an idea about the size of the zip file written by the backend and the size of the zip file that gets downloaded by the chosen browser. Thank you.

**Comment by avinashreddy07** [comment]
Hi @nysenthil , NLP Editor is hosted on Ubuntu 22.04.

I tried exporting zip from -

- Chrome Version 108.0.5359.98
- Firefox Version 108.0
- Safari Version 16.2 (18614.3.7.1.5)

I faced the same issue while unzipping the exported zip.

My Mac OS version is macOS Ventura 13.1 (22C65)

**Comment by praveenmidde** [comment]
@nysenthil / @marthacryan .. Can we prioritize this issue? Looks like we can't yet use the built extractors in our product. Thanks.

**Comment by nysenthil** [comment]
Hi @praveenmidde All the new versions of the browsers (Firefox, Chrome, Safari) seem to have problem exporting the flow. We are going to look into it this week.

**Comment by marthacryan** [comment]
@nysenthil @avinashreddy07 @praveenmidde Sorry for the slow reply over the holidays - I just tried this out and wasn't able to reproduce it on either Chrome or Firefox. The inconsistency with this is making me wonder if there's some browser caching happening? I could also see it happening inconsistently if there's an issue with the streaming of the zip file contents but unfortunately if I can't reproduce it locally I won't be able to debug

**Comment by laurachiticariu** [comment]
@avinashreddy07 this was fixed. Please let us know if you still encounter issues.

**Comment by avinashreddy07** [comment]
@laurachiticariu, now I could download the zip. Thank you for fixing this issue.
