### ISSUE TITLE
Dictionary: add "Upload from file" functionality

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#41]
The current Discovery panel allows to type the entries in the UI. This is tedious if the dictionary should contain more than a few terms. 

Solution:
 The UI should provide an Upload from file button that allows the user to upload the dictionary from a file.

**Comment by marthacryan** [comment]
What would the file contents look like?

**Comment by laurachiticariu** [comment]
The file would be a plain text file, with one entry per line. Some examples can be found here: https://github.com/CODAIT/nlp-editor/tree/main/sample-data/revenue%20by%20division (abbreviations.txt and divisions.txt).
