### ISSUE TITLE
Filter: update caption and change `range` to `span`

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#47]
For the filter node, the caption should be changed to "Remove some annotations from the output". Currently the caption is the same as for Consolidate.

<img width="308" alt="image" src="https://user-images.githubusercontent.com/16584976/173822119-0033b768-5c21-4b73-b5bc-503728c69e57.png">

Also, we should rename "range" to "span" in the filter settings.

**Comment by JesusGuerrero** [comment]
Msg: Remove annotations from the output

rename `range` to `span`
