### ISSUE TITLE
Copy paste a sequence does not allow editing the copy

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#48]
To reproduce:
1. Create a sequence and save it
2. Copy the sequence and paste it on the canvas
3. Double-click the copy. The message "select a node to edit its properties" appears in the right panel. The copy sequence cannot be edited even after connecting it with some input nodes.

![copy_sequence](https://user-images.githubusercontent.com/16584976/173824413-15a3c14f-a8cb-4a9c-bfd6-fa1b8994ac39.gif)

**Comment by JesusGuerrero** [comment]
similar behavior to https://github.com/CODAIT/nlp-editor/issues/50

we need to ensure sync of elyra/canvas with nlp-editor is handled correctly
