### ISSUE TITLE
Changing an attribute of a sequence is not persisted

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#49]
1. Create two sequences
2. Change the attribute name of the first sequence and save it.
3. Open the second sequence
4. Open the first sequence. The attribute renaming is lost on the first sequence

In this case, the two sequences were involved in a union, which I had deleted. I believe the Union propagated some attributes to the input sequences, which might cause this ssue.

![union_overrides_attribute_names](https://user-images.githubusercontent.com/16584976/173825977-c8945b9c-10ba-4d77-8e55-5a84bd1883cb.gif)

**Comment by JesusGuerrero** [comment]
closing the panel and reopening shows the correct value, however, when you switch between the same node type the old values don't get flushed/reset
