### ISSUE TITLE
Adding a new sequence reaches a bad state

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#50]
I got into a situation where after deleting a few sequence nodes, adding a new sequence connected to the same input nodes as the deleted sequence cannot be edited anymore.

![union_overrides_attribute_names](https://user-images.githubusercontent.com/16584976/173827042-95a86ee4-f7c6-47b6-b203-5b9b94d56ced.gif)

**Comment by JesusGuerrero** [comment]
this is reproducible with copy & paste a node, the canvas needs to communicate with host app to ensure new entry of a node
