### ISSUE TITLE
Fix tooltips for some of the constructs

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#53]
I noticed a few extraneous tooltips for the constructs in the left panel. The tooltips seem to be image names. We should suppress them.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/16584976/173962708-1aedb4c5-d779-4e7c-a589-b4f32b449210.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/16584976/173962909-dbcd2ae4-5d69-4fb3-aab5-af41132bf20e.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/16584976/173962960-1281ee03-f3b6-49ee-8ac5-0d50aa19892d.png">

**Comment by JesusGuerrero** [comment]
we should also have palette open with categories expanded by default
