### ISSUE TITLE
Result Table Viewer: show tooltip for view names or allow resizing to show the full name

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#67]
In the result table view, it is not possible to distinguish between the names of nodes starting `RevenueOfDivisio`. The UI should allow resixing of those tabs, or provide a tooltip showing the full name, or show the full name when one clicks on the tab. Otherwise, the user does not have a way to match the result tables with the corresponding node.

![image](https://user-images.githubusercontent.com/16584976/174912713-a58126cd-358b-4d1a-978d-cb40c28fb632.png)

**Comment by marthacryan** [comment]
I think when you hover over a node you're able to see a tooltip with the full title? 
![image](https://user-images.githubusercontent.com/6673460/175423454-78281994-a6d9-49ca-9ba8-7f3c1dfe79ef.png)

**Comment by laurachiticariu** [comment]
@marthacryan Yes, but I can't see the full title in the result table in the bottom pane, the 3 tabs showing `RevenueByDivisio...`. So, I can't match the result with the corresponding node.

![image](https://user-images.githubusercontent.com/16584976/175451235-68b3d384-4787-4f97-a8ee-77d5428eb36f.png)

**Comment by marthacryan** [comment]
Ah ok got it - I'll check it out

**Comment by marthacryan** [comment]
@laurachiticariu Can we close this given that #106 is merged?

**Comment by laurachiticariu** [comment]
@marthacryan yes we can close it since the tooltip contains all the information. If users think it is more user-friendly to have adjustable-width tabs as you mentioned in https://github.com/CODAIT/nlp-editor/pull/106#issue-1389768998, they can open a new issue later.
