### ISSUE TITLE
Enhanced Export ability

### ISSUE THREAD

**Issue by laurachiticariu** [CODAIT/nlp-editor#73]
Same as #72 but for the Export capability. Currently the Export saves the model into an autogenerated `.zip` file into the default Downloads folder. The enhanced capability should allow the use to select the folder name and the model zip file name that the model is saved to.

**Comment by marthacryan** [comment]
Looks like this might be the best option: https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker
