### ISSUE TITLE
Starting nlp-editor in nodejs development server mode causes CORS error

### ISSUE THREAD

**Issue by agiagoulas** [CODAIT/nlp-editor#78]
Starting nlp-editor in nodejs development server mode (npm install, npm start) causes CORS error when uploading a txt file in the Input Documents field. The upload api call therefore returns a 504 error

`[HPM] Error occurred while proxying request localhost:3000/api/upload to http://localhost:8080/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)`

**Comment by laurachiticariu** [comment]
The root cause was that the backend was not started.
