### ISSUE TITLE
Add ability to Consolidate results from NLP extractors

### ISSUE THREAD

**Issue by zeusorionIBM** [CODAIT/nlp-editor#8]
**Description:**
An extractor sometimes generates multiple rows for the same text because the text matches more than one dictionary entry. To remove or consolidate the duplicate entries, you must provide consolidation rules. More information can be found [here](https://cloud.ibm.com/docs/watson-knowledge-studio?topic=watson-knowledge-studio-managing-projects-and-extractors#removing-duplicate-and-overlapping-results).

**Tasks:**
The consolidate node and panel are already part of the Elyra NLP Canvas. We need to:

- [ ] validate that all required input from the user is entered and correct
- [ ]  transform user's input into payload that SystemT can then translate and run as AQL.

**Comment by laurachiticariu** [comment]
Completed in #38
