### ISSUE TITLE
npm install does not work due to conflicting dependencies

### ISSUE THREAD

**Issue by agiagoulas** [CODAIT/nlp-editor#80]
`npm install` only works when using `npm i --force` which cannot be correct

**Comment by laurachiticariu** [comment]
@agiagoulas is this still reproducible? If not, can you please close it?

**Comment by agiagoulas** [comment]
Okay, I think then I can close the issue

**Comment by laurachiticariu** [comment]
Thanks @IBMOlaf we removed the step to create the directories (and yes, `Seer-Code` was a typo, thanks for pointing it out).
