### ISSUE TITLE
Creating multiple extractors in NLP Visual Editor exports the zip file with same TAM file names.

### ISSUE THREAD

**Issue by VShriva6** [CODAIT/nlp-editor#87]
In Datacap product we allow customer to deploy extractors by pasting all TAM files in one of the installed location. Customers many times create multiple extractors for their different requirements.
For example they might create one extractor to extract all Revenues and another separate extractor to extract the product who generated maximum revenue.
So first they will create extractor Revenue and export it . They will get their TAM files.
Then they might create another extractor "ProductDetails" and export it . They will get another set of TAM files. 

If you will notice the name of the TAM files from both the extractor will be same.
If customer deploy first set of TAM files then it will work in Datacap. But as soon as they deploy another set of TAM files, tthen second set of TAM files will replace first set of TAM files.
Which means latest deployed extractor TAM files will only work in Datcacap at a time.

I hope issue is clear.

**Comment by nysenthil** [comment]
Hi @VShriva6 Thank you for creating this issue. I made a new enhancement in the SystemT + AQL Backend docker container to address this issue. With that enhancement, you will see that the exported zip archive will have TAM file names created with a unique numeric identifier (e-g: biadmin_elyraNLPCanvas_1659990319.tam and biadmin_elyraNLPCanvas__Export_1659990319.tam) thereby not causing name collisions across different exported archives. Our colleague Michael tested this enhancement in DataCap and he confirmed that it works well. You can also test it in your environment.
